### ISSUE TITLE
Usage Example

### ISSUE THREAD

**Issue by geggleto** [AdamKyle/EvePublicCrest#3]
As someone who literally hates all things laravel, it would be really nice to use a good usage example of how to use this with Laravel.

The library seems to just pull and dump the contents of an End Point to a log file, which is pretty useless :)

I could accomplish the same thing using curl ;)

**Comment by AdamKyle** [comment]
The Library actually returns you a set of JSON. For example if you look at: [this example](https://github.com/AdamKyle/EvePublicCrest/blob/master/src/Market/History/README.md#usage) you will see at the bottom I do:

``` php
EveItemHistory::createRequests($items, $regions);

$fetchedItemHistory = EveItemHistory::getItemHistoryForRegion();
$historicalData     = EveItemHistory::getHistoricalData();
```

which returns you an array of arrays, with each nested array looking like:

``` php
618 => array:3 [
  "regionId" => "10000068"
  "itemId" => "38"
  "responseJson" => {#152015 …5}
]
```

I log responses to the log files but also give you the response back so you can do what ever you wish with it. I will work on the documentation more to flush it out. Thanks for this.

**Comment by AdamKyle** [comment]
There is more explanations on the usage of the various facades and how you would set them up and use them as well as what they return, be it containers or decoded JSON.

Should you need more information or have a question please feel free to ask :)
